// ============================================================
// v2 讀音與諧音（手工維護）
// V2_PINYIN：字 → 國語拼音（不含聲調、ü 寫 v）。涵蓋字庫（v2-pool.js）與字義字典（v2-gloss.js）的所有字。
//            多音字取命名常用讀音（柏＝bo、茜＝qian、樂＝le）。
// V2_SURNAME_PY：常見姓氏讀音。
// V2_HOMOPHONES：唸起來像「尷尬詞」的字典 [詞, 拼音]。比對時忽略聲調，並把台灣國語常混的音當同音：
//            前後鼻音（n/ng）、捲舌（zh/z、ch/c、sh/s）。所以 洛丞(luo cheng) 會對到 落塵(luo chen)。
// 這本字典不可能窮盡，網頁上會標明「沒對到不代表沒問題」。
// ============================================================
var V2_PINYIN = {
  // ---- 字庫 ----
  宥:'you', 恩:'en', 樂:'le', 希:'xi', 宇:'yu', 安:'an', 羽:'yu', 允:'yun', 亦:'yi', 恆:'heng', 品:'pin', 書:'shu', 洛:'luo', 沐:'mu',
  昀:'yun', 梓:'zi', 若:'ruo', 語:'yu', 寧:'ning', 晴:'qing', 晨:'chen', 睿:'rui', 靖:'jing', 澄:'cheng', 霖:'lin', 辰:'chen', 昱:'yu',
  柏:'bo', 奕:'yi', 翊:'yi', 禾:'he', 之:'zhi', 予:'yu', 川:'chuan', 一:'yi', 立:'li', 心:'xin', 采:'cai', 唯:'wei', 昭:'zhao', 瑄:'xuan',
  言:'yan', 知:'zhi', 以:'yi', 嘉:'jia', 家:'jia', 庭:'ting', 恬:'tian', 沂:'yi', 祐:'you', 佑:'you', 承:'cheng', 秉:'bing', 哲:'zhe',
  祈:'qi', 致:'zhi', 則:'ze', 耀:'yao', 沛:'pei', 侑:'you', 旻:'min', 宸:'chen', 翰:'han', 澤:'ze', 逸:'yi', 笙:'sheng', 瑀:'yu',
  曜:'yao', 丞:'cheng', 聿:'yu', 澔:'hao', 赫:'he', 璟:'jing', 暘:'yang', 崴:'wei', 瑋:'wei', 彥:'yan', 凱:'kai', 廷:'ting', 翔:'xiang',
  諺:'yan', 寬:'kuan', 謙:'qian', 硯:'yan', 朗:'lang', 卓:'zhuo', 泓:'hong', 竑:'hong', 昊:'hao', 明:'ming', 軒:'xuan', 東:'dong',
  原:'yuan', 宗:'zong', 勳:'xun', 駿:'jun', 冠:'guan', 均:'jun', 毅:'yi', 賢:'xian', 建:'jian', 緯:'wei', 峻:'jun', 宏:'hong',
  成:'cheng', 桓:'huan', 德:'de', 國:'guo', 正:'zheng', 啟:'qi', 弘:'hong', 振:'zhen', 健:'jian', 光:'guang', 崇:'chong', 偉:'wei',
  銘:'ming', 豪:'hao', 榮:'rong', 豐:'feng', 年:'nian', 志:'zhi', 文:'wen', 傑:'jie', 俊:'jun', 信:'xin', 智:'zhi', 仁:'ren', 齊:'qi',
  昕:'xin', 宜:'yi', 欣:'xin', 妍:'yan', 映:'ying', 姵:'pei', 柔:'rou', 思:'si', 芯:'xin', 芷:'zhi', 芮:'rui', 苡:'yi', 婕:'jie',
  悅:'yue', 茉:'mo', 瑤:'yao', 萱:'xuan', 蓁:'zhen', 穎:'ying', 璇:'xuan', 曉:'xiao', 霏:'fei', 蓉:'rong', 彤:'tong', 妤:'yu', 伊:'yi',
  甯:'ning', 晞:'xi', 晏:'yan', 芃:'peng', 榆:'yu', 筠:'yun', 緹:'ti', 翎:'ling', 涵:'han', 芸:'yun', 菲:'fei', 玥:'yue', 珞:'luo',
  妡:'xin', 芊:'qian', 詠:'yong', 舒:'shu', 澐:'yun', 湘:'xiang', 綺:'qi', 妮:'ni', 佳:'jia', 禧:'xi', 霞:'xia', 慧:'hui', 盈:'ying',
  姿:'zi', 如:'ru', 珍:'zhen', 瑩:'ying', 婉:'wan', 玉:'yu', 彩:'cai', 君:'jun', 瑜:'yu', 紫:'zi', 嫣:'yan', 淑:'shu', 美:'mei',
  惠:'hui', 玲:'ling', 雅:'ya', 婷:'ting', 怡:'yi', 華:'hua', 秀:'xiu', 珊:'shan', 琪:'qi', 琳:'lin', 詩:'shi',
  // ---- 字義字典 ----
  桐:'tong', 梧:'wu', 楷:'kai', 楠:'nan', 樺:'hua', 楊:'yang', 松:'song', 杉:'shan', 桂:'gui', 楓:'feng', 榕:'rong', 檀:'tan', 棠:'tang',
  棋:'qi', 楨:'zhen', 森:'sen', 林:'lin', 樹:'shu', 權:'quan', 棟:'dong', 材:'cai', 杰:'jie', 果:'guo', 栩:'xu', 桑:'sang', 榛:'zhen',
  樟:'zhang', 柳:'liu', 楚:'chu', 海:'hai', 浩:'hao', 淵:'yuan', 溪:'xi', 湖:'hu', 源:'yuan', 潤:'run', 漢:'han', 濤:'tao', 瀚:'han',
  淳:'chun', 渝:'yu', 清:'qing', 深:'shen', 泉:'quan', 汝:'ru', 淇:'qi', 沁:'qin', 淼:'miao', 漪:'yi', 渺:'miao', 泰:'tai', 洋:'yang',
  河:'he', 江:'jiang', 波:'bo', 潔:'jie', 澈:'che', 沅:'yuan', 沄:'yun', 汐:'xi', 汶:'wen', 洵:'xun', 涓:'juan', 淨:'jing', 浚:'jun',
  治:'zhi', 泳:'yong', 洲:'zhou', 溢:'yi', 濬:'jun', 鋒:'feng', 鈺:'yu', 鑫:'xin', 錦:'jin', 鍾:'zhong', 銓:'quan', 鈞:'jun', 鎧:'kai',
  錫:'xi', 珮:'pei', 瑞:'rui', 琛:'chen', 璃:'li', 璨:'can', 瑾:'jin', 珩:'heng', 珣:'xun', 琰:'yan', 琮:'cong', 珂:'ke', 珈:'jia',
  璐:'lu', 瓊:'qiong', 璧:'bi', 玫:'mei', 珠:'zhu', 琦:'qi', 昌:'chang', 晃:'huang', 晟:'sheng', 暉:'hui', 曦:'xi', 晶:'jing',
  昶:'chang', 昂:'ang', 旭:'xu', 晝:'zhou', 曄:'ye', 暐:'wei', 晗:'han', 晉:'jin', 炎:'yan', 煜:'yu', 煒:'wei', 熙:'xi', 燁:'ye',
  燦:'can', 焱:'yan', 炫:'xuan', 煥:'huan', 烽:'feng', 炘:'xin', 煦:'xu', 燊:'shen', 熠:'yi', 輝:'hui', 坤:'kun', 培:'pei', 堯:'yao',
  城:'cheng', 坦:'tan', 垚:'yao', 圭:'gui', 堂:'tang', 基:'ji', 堅:'jian', 埕:'cheng', 岳:'yue', 峰:'feng', 崧:'song', 嵐:'lan',
  嶸:'rong', 岑:'cen', 岱:'dai', 岡:'gang', 宣:'xuan', 宛:'wan', 宬:'cheng', 密:'mi', 寰:'huan', 宙:'zhou', 定:'ding', 寶:'bao',
  寅:'yin', 富:'fu', 仰:'yang', 任:'ren', 伯:'bo', 佩:'pei', 依:'yi', 侯:'hou', 倫:'lun', 儀:'yi', 儒:'ru', 傳:'chuan', 億:'yi',
  仲:'zhong', 伶:'ling', 佟:'tong', 伃:'yu', 修:'xiu', 娜:'na', 姍:'shan', 娟:'juan', 媛:'yuan', 嬅:'hua', 嫻:'xian', 姝:'shu',
  妙:'miao', 娣:'di', 嫚:'man', 婧:'jing', 妲:'da', 姞:'ji', 娉:'ping', 娃:'wa', 姬:'ji', 嬌:'jiao', 媚:'mei', 嫄:'yuan', 妘:'yun',
  娥:'e', 婭:'ya', 妃:'fei', 芝:'zhi', 芳:'fang', 芬:'fen', 茜:'qian', 荷:'he', 莉:'li', 菱:'ling', 萍:'ping', 蓮:'lian', 蕊:'rui',
  薇:'wei', 蘭:'lan', 蔚:'wei', 荃:'quan', 莎:'sha', 苓:'ling', 茗:'ming', 蕙:'hui', 藝:'yi', 菀:'wan', 蓓:'bei', 荏:'ren', 苗:'miao',
  莘:'shen', 菡:'han', 芩:'qin', 茹:'ru', 苹:'ping', 英:'ying', 茂:'mao', 莊:'zhuang', 菁:'jing', 萌:'meng', 葉:'ye', 蒂:'di', 蔓:'man',
  蕾:'lei', 藍:'lan', 藤:'teng', 蘋:'ping', 蘇:'su', 悠:'you', 愉:'yu', 慕:'mu', 意:'yi', 愷:'kai', 憶:'yi', 慈:'ci', 愛:'ai',
  憲:'xian', 懿:'yi', 忻:'xin', 恕:'shu', 惟:'wei', 憬:'jing', 訓:'xun', 記:'ji', 詞:'ci', 詮:'quan', 誌:'zhi', 說:'shuo', 諄:'zhun',
  諦:'di', 譽:'yu', 誠:'cheng', 諾:'nuo', 讓:'rang', 元:'yuan', 天:'tian', 云:'yun', 丹:'dan', 方:'fang', 中:'zhong', 世:'shi',
  平:'ping', 永:'yong', 民:'min', 冬:'dong', 玄:'xuan', 白:'bai', 可:'ke', 令:'ling', 石:'shi', 匡:'kuang', 名:'ming', 向:'xiang',
  竹:'zhu', 舟:'zhou', 行:'xing', 亨:'heng', 兆:'zhao', 吉:'ji', 同:'tong', 聖:'sheng', 勇:'yong', 政:'zheng', 勤:'qin', 敬:'jing',
  新:'xin', 業:'ye', 雲:'yun', 雨:'yu', 霄:'xiao', 雷:'lei', 霆:'ting', 霜:'shuang', 露:'lu', 韻:'yun', 音:'yin', 貴:'gui', 賜:'si',
  贊:'zan', 超:'chao', 越:'yue', 遠:'yuan', 達:'da', 道:'dao', 遜:'xun', 通:'tong', 逢:'feng', 運:'yun', 進:'jin', 陽:'yang',
  隆:'long', 陸:'lu', 陶:'tao', 靜:'jing', 青:'qing', 韋:'wei', 頌:'song', 順:'shun', 領:'ling', 顥:'hao', 願:'yuan', 馨:'xin',
  驊:'hua', 騰:'teng', 鶴:'he', 鵬:'peng', 麗:'li', 龍:'long', 群:'qun', 義:'yi', 羚:'ling', 翠:'cui', 聰:'cong', 育:'yu', 能:'neng',
  臻:'zhen', 至:'zhi', 良:'liang', 虹:'hong', 融:'rong', 衍:'yan', 衛:'wei', 裕:'yu', 裴:'pei', 西:'xi', 覺:'jue', 觀:'guan',
  貞:'zhen', 財:'cai', 資:'zi', 賓:'bin', 起:'qi', 輔:'fu', 遙:'yao', 邦:'bang', 郁:'yu', 醇:'chun', 里:'li', 重:'zhong', 野:'ye',
  量:'liang', 鈴:'ling', 鎮:'zhen', 長:'zhang', 開:'kai', 閎:'hong', 閱:'yue', 闊:'kuo', 際:'ji', 雁:'yan', 集:'ji', 雋:'jun',
  雙:'shuang', 靈:'ling', 非:'fei', 靚:'jing', 韶:'shao', 頎:'qi', 頤:'yi', 頡:'jie', 顏:'yan', 風:'feng', 飛:'fei', 香:'xiang',
  馥:'fu', 高:'gao', 魁:'kui', 鴻:'hong', 麒:'qi', 黎:'li', 默:'mo', 鼎:'ding', 齡:'ling', 勝:'sheng', 凡:'fan', 祥:'xiang',
  禎:'zhen', 祺:'qi', 福:'fu', 禹:'yu', 秦:'qin', 秋:'qiu', 科:'ke', 程:'cheng', 稚:'zhi', 穆:'mu', 竣:'jun', 章:'zhang', 笛:'di',
  筑:'zhu', 箏:'zheng', 簡:'jian', 紘:'hong', 紳:'shen', 絃:'xian', 統:'tong', 絜:'jie', 綸:'lun', 綾:'ling', 緣:'yuan', 縈:'ying',
  繹:'yi', 纖:'xian', 耘:'yun', 肯:'ken', 胤:'yin', 臣:'chen', 舜:'shun', 艾:'ai', 子:'zi', 金:'jin',
};

var V2_SURNAME_PY = {
  李:'li', 王:'wang', 陳:'chen', 林:'lin', 張:'zhang', 黃:'huang', 吳:'wu', 劉:'liu', 蔡:'cai', 楊:'yang', 許:'xu', 鄭:'zheng', 謝:'xie',
  郭:'guo', 洪:'hong', 曾:'zeng', 邱:'qiu', 廖:'liao', 賴:'lai', 徐:'xu', 周:'zhou', 葉:'ye', 蘇:'su', 莊:'zhuang', 呂:'lv', 江:'jiang',
  何:'he', 蕭:'xiao', 羅:'luo', 高:'gao', 潘:'pan', 簡:'jian', 朱:'zhu', 鍾:'zhong', 游:'you', 彭:'peng', 詹:'zhan', 胡:'hu', 施:'shi',
  沈:'shen', 余:'yu', 盧:'lu', 梁:'liang', 趙:'zhao', 顏:'yan', 柯:'ke', 翁:'weng', 魏:'wei', 孫:'sun', 戴:'dai', 范:'fan', 方:'fang',
  宋:'song', 鄧:'deng', 杜:'du', 傅:'fu', 侯:'hou', 曹:'cao', 薛:'xue', 丁:'ding', 卓:'zhuo', 馬:'ma', 董:'dong', 唐:'tang', 溫:'wen',
  藍:'lan', 石:'shi', 姚:'yao', 紀:'ji', 康:'kang', 田:'tian', 白:'bai', 秦:'qin',
};

// [尷尬詞, 拼音]。兩字詞會拿來對「名1名2」和「姓＋名1」；三字詞對整個姓名。
var V2_HOMOPHONES = [
  // 使用者提出的
  ['落塵','luo chen'], ['若愚','ruo yu'], ['虹吸','hong xi'], ['生意','sheng yi'], ['乘以','cheng yi'],
  ['成語','cheng yu'], ['一成','yi cheng'], ['一成不變','yi cheng bu bian'], ['臣妾','chen qie'], ['沉魚','chen yu'],
  // 生死病痛
  ['死亡','si wang'], ['死人','si ren'], ['死刑','si xing'], ['死屍','si shi'], ['死者','si zhe'], ['死路','si lu'], ['死心','si xin'],
  ['死機','si ji'], ['死掉','si diao'], ['去死','qu si'], ['找死','zhao si'], ['尋死','xun si'], ['嚇死','xia si'], ['氣死','qi si'],
  ['痛死','tong si'], ['凍死','dong si'], ['淹死','yan si'], ['橫死','heng si'], ['壓死','ya si'], ['勒死','le si'], ['咬死','yao si'],
  ['逝世','shi shi'], ['過世','guo shi'], ['離世','li shi'], ['陣亡','zhen wang'], ['短命','duan ming'], ['夭折','yao zhe'], ['折壽','zhe shou'],
  ['永別','yong bie'], ['永眠','yong mian'], ['昇天','sheng tian'], ['善終','shan zhong'], ['安息','an xi'], ['安葬','an zang'], ['下葬','xia zang'],
  ['陪葬','pei zang'], ['合葬','he zang'], ['入土','ru tu'], ['入殮','ru lian'], ['停屍','ting shi'], ['陳屍','chen shi'], ['撿屍','jian shi'],
  ['屍體','shi ti'], ['屍首','shi shou'], ['屍骨','shi gu'], ['遺體','yi ti'], ['遺骸','yi hai'], ['遺言','yi yan'], ['遺書','yi shu'], ['遺願','yi yuan'],
  ['棺材','guan cai'], ['開棺','guan guan'], ['靈堂','ling tang'], ['靈柩','ling jiu'], ['靈車','ling che'], ['冥紙','ming zhi'], ['冥界','ming jie'],
  ['紙錢','zhi qian'], ['紙紮','zhi zha'], ['招魂','zhao hun'], ['回魂','hui hun'], ['冤魂','yuan hun'], ['遊魂','you hun'], ['鬼魂','gui hun'],
  ['亡靈','wang ling'], ['幽靈','you ling'], ['殭屍','jiang shi'], ['厲鬼','li gui'], ['見鬼','jian gui'], ['小鬼','xiao gui'], ['閻王','yan wang'],
  ['陰間','yin jian'], ['地獄','di yu'], ['黃泉','huang quan'], ['命案','ming an'], ['命短','ming duan'], ['命薄','ming bo'], ['玩命','wan ming'],
  ['癌症','ai zheng'], ['腫瘤','zhong liu'], ['肺癌','fei ai'], ['肺炎','fei yan'], ['發炎','fa yan'], ['炎症','yan zheng'], ['得病','de bing'],
  ['得癌','de ai'], ['生病','sheng bing'], ['有病','you bing'], ['病人','bing ren'], ['病死','bing si'], ['病危','bing wei'], ['病態','bing tai'],
  ['病毒','bing du'], ['細菌','xi jun'], ['瘟疫','wen yi'], ['鼠疫','shu yi'], ['淋病','lin bing'], ['性病','xing bing'], ['痢疾','li ji'],
  ['痔瘡','zhi chuang'], ['濕疹','shi zhen'], ['便秘','bian mi'], ['頻尿','pin niao'], ['失禁','shi jin'], ['失明','shi ming'], ['失智','shi zhi'],
  ['癡呆','chi dai'], ['中風','zhong feng'], ['中毒','zhong du'], ['中邪','zhong xie'], ['中槍','zhong qiang'], ['洗腎','xi shen'], ['化療','hua liao'],
  ['化膿','hua nong'], ['截肢','jie zhi'], ['殘廢','can fei'], ['瞎子','xia zi'], ['瞎眼','xia yan'], ['聾子','long zi'], ['啞巴','ya ba'],
  ['跛腳','bo jiao'], ['暈倒','yun dao'], ['暈船','yun chuan'], ['孕吐','yun tu'], ['流產','liu chan'], ['早洩','zao xie'], ['陽痿','yang wei'],
  ['月經','yue jing'], ['經血','jing xue'], ['經期','jing qi'], ['精液','jing ye'], ['精蟲','jing chong'], ['生殖','sheng zhi'], ['子宮','zi gong'],
  ['乳房','ru fang'], ['乳頭','ru tou'], ['乳暈','ru yun'], ['胸罩','xiong zhao'], ['膀胱','pang guang'], ['肚臍','du qi'], ['屁股','pi gu'],
  ['放屁','fang pi'], ['大便','da bian'], ['小便','xiao bian'], ['尿尿','niao niao'], ['屎尿','shi niao'], ['狗屎','gou shi'], ['雞屎','ji shi'],
  ['眼屎','yan shi'], ['牛糞','niu fen'], ['嘔吐','ou tu'], ['想吐','xiang tu'], ['口臭','kou chou'], ['汗臭','han chou'], ['體臭','ti chou'],
  ['臭味','chou wei'], ['狐臭','hu chou'], ['牙痛','ya tong'], ['胃痛','wei tong'], ['腰痛','yao tong'], ['心痛','xin tong'], ['痛苦','tong ku'],
  // 罵人、貶義
  ['白癡','bai chi'], ['智障','zhi zhang'], ['弱智','ruo zhi'], ['低能','di neng'], ['無能','wu neng'], ['無恥','wu chi'], ['腦殘','nao can'],
  ['傻子','sha zi'], ['瘋子','feng zi'], ['瘋狗','feng gou'], ['笨蛋','ben dan'], ['混蛋','hun dan'], ['壞蛋','huai dan'], ['完蛋','wan dan'],
  ['廢物','fei wu'], ['廢人','fei ren'], ['廢柴','fei chai'], ['廢話','fei hua'], ['沒用','mei yong'], ['垃圾','le se'], ['垃圾','la ji'],
  ['飯桶','fan tong'], ['馬桶','ma tong'], ['豬頭','zhu tou'], ['豬肉','zhu rou'], ['肥豬','fei zhu'], ['肥胖','fei pang'], ['花癡','hua chi'],
  ['音癡','yin chi'], ['犯賤','fan jian'], ['下賤','xia jian'], ['賤人','jian ren'], ['賤貨','jian huo'], ['下流','xia liu'], ['人渣','ren zha'],
  ['人妖','ren yao'], ['妖怪','yao guai'], ['妖精','yao jing'], ['妖魔','yao mo'], ['妖孽','yao nie'], ['色狼','se lang'], ['變態','bian tai'],
  ['妓女','ji nv'], ['嫖客','piao ke'], ['小偷','xiao tou'], ['強盜','qiang dao'], ['騙子','pian zi'], ['賭徒','du tu'], ['酒鬼','jiu gui'],
  ['毒品','du pin'], ['吸毒','xi du'], ['戒毒','jie du'], ['囚犯','qiu fan'], ['犯人','fan ren'], ['坐牢','zuo lao'], ['監獄','jian yu'],
  ['入獄','ru yu'], ['越獄','yue yu'], ['通緝','tong ji'], ['通姦','tong jian'], ['姦淫','jian yin'], ['奸詐','jian zha'], ['陰險','yin xian'],
  ['淫穢','yin hui'], ['禽獸','qin shou'], ['王八','wang ba'], ['烏龜','wu gui'], ['蟑螂','zhang lang'], ['老鼠','lao shu'], ['蒼蠅','cang ying'],
  ['蚊子','wen zi'], ['蛔蟲','hui chong'], ['蟲子','chong zi'], ['生蟲','sheng chong'], ['蠕蟲','ru chong'], ['蜘蛛','zhi zhu'], ['泥鰍','ni qiu'],
  ['流氓','liu mang'], ['兇手','xiong shou'], ['殺人','sha ren'], ['自殺','zi sha'], ['自殘','zi can'], ['自卑','zi bei'], ['自私','zi si'],
  ['丟臉','diu lian'], ['羞恥','xiu chi'], ['羞辱','xiu ru'], ['辱罵','ru ma'], ['笑柄','xiao bing'], ['笑話','xiao hua'], ['神經','shen jing'],
  ['發神經','fa shen jing'], ['神經病','shen jing bing'], ['沒良心','mei liang xin'], ['沒出息','mei chu xi'],
  // 倒楣、失敗、窮困
  ['倒楣','dao mei'], ['晦氣','hui qi'], ['衰運','shuai yun'], ['霉運','mei yun'], ['發霉','fa mei'], ['霉菌','mei jun'], ['冤枉','yuan wang'],
  ['冤獄','yuan yu'], ['失敗','shi bai'], ['失業','shi ye'], ['失蹤','shi zong'], ['失身','shi shen'], ['失戀','shi lian'], ['失控','shi kong'],
  ['破產','po chan'], ['負債','fu zhai'], ['欠債','qian zhai'], ['欠錢','qian qian'], ['沒錢','mei qian'], ['貧窮','pin qiong'], ['貧困','pin kun'],
  ['貧血','pin xue'], ['吃虧','chi kui'], ['倒閉','dao bi'], ['停業','ting ye'], ['開除','kai chu'], ['離職','li zhi'], ['離婚','li hun'],
  ['落選','luo xuan'], ['落榜','luo bang'], ['落魄','luo po'], ['落難','luo nan'], ['落後','luo hou'], ['落淚','luo lei'], ['落水','luo shui'],
  ['落跑','luo pao'], ['輸錢','shu qian'], ['輸家','shu jia'], ['輸光','shu guang'], ['輸掉','shu diao'], ['賠錢','pei qian'], ['賠償','pei chang'],
  ['浪費','lang fei'], ['狼狽','lang bei'], ['懦弱','nuo ruo'], ['弱者','ruo zhe'], ['弱雞','ruo ji'], ['愚蠢','yu chun'], ['愚昧','yu mei'],
  ['沉淪','chen lun'], ['沉溺','chen ni'], ['沉船','chen chuan'], ['船難','chuan nan'], ['遇難','yu nan'], ['遇害','yu hai'], ['意外','yi wai'],
  ['事故','shi gu'], ['天災','tian zai'], ['天譴','tian qian'], ['災難','zai nan'], ['劫難','jie nan'], ['浩劫','hao jie'], ['劫匪','jie fei'],
  ['危險','wei xian'], ['危機','wei ji'], ['威脅','wei xie'], ['陷害','xian hai'], ['陷阱','xian jing'], ['嫌棄','xian qi'], ['嫌疑','xian yi'],
  ['欺負','qi fu'], ['欺騙','qi pian'], ['乞丐','qi gai'], ['乞討','qi tao'], ['歧視','qi shi'], ['淒涼','qi liang'], ['淒慘','qi can'],
  ['折磨','zhe mo'], ['折斷','zhe duan'], ['懲罰','cheng fa'], ['憂鬱','you yu'], ['猶豫','you yu'], ['幼稚','you zhi'], ['幼齒','you chi'],
  ['壓力','ya li'], ['心虛','xin xu'], ['心機','xin ji'], ['心酸','xin suan'], ['辛酸','xin suan'], ['悔恨','hui hen'], ['怨恨','yuan hen'],
  ['厭世','yan shi'], ['厭食','yan shi'], ['輕生','qing sheng'], ['絕望','jue wang'], ['抑鬱','yi yu'], ['迷失','mi shi'],
  // 情色、婚姻尷尬
  ['情婦','qing fu'], ['情敵','qing di'], ['小三','xiao san'], ['約炮','yue pao'], ['上床','shang chuang'], ['陪睡','pei shui'], ['性感','xing gan'],
  ['性慾','xing yu'], ['慾望','yu wang'], ['裸體','luo ti'], ['裸露','luo lu'], ['寬衣','kuan yi'], ['私奔','si ben'], ['私生','si sheng'],
  ['未婚','wei hun'], ['嫁人','jia ren'], ['熟女','shu nv'], ['剩女','sheng nv'], ['老公','lao gong'], ['老婆','lao po'], ['光棍','guang gun'],
  // 日常物品、動作（唸出來像東西）
  ['沐浴','mu yu'], ['木魚','mu yu'], ['雨衣','yu yi'], ['浴衣','yu yi'], ['浴缸','yu gang'], ['魚翅','yu chi'], ['芋頭','yu tou'], ['芋泥','yu ni'],
  ['玉米','yu mi'], ['雨傘','yu san'], ['油條','you tiao'], ['油炸','you zha'], ['油膩','you ni'], ['鹹魚','xian yu'], ['香腸','xiang chang'],
  ['香菇','xiang gu'], ['菜刀','cai dao'], ['菜市','cai shi'], ['菜鳥','cai niao'], ['菜色','cai se'], ['剩菜','sheng cai'], ['剩飯','sheng fan'],
  ['蛋黃','dan huang'], ['豆干','dou gan'], ['羊肉','yang rou'], ['洋蔥','yang cong'], ['冬瓜','dong gua'], ['西施','xi shi'], ['西藥','xi yao'],
  ['膝蓋','xi gai'], ['鼻涕','bi ti'], ['口水','kou shui'], ['泥巴','ni ba'], ['泥土','ni tu'], ['垃圾桶','le se tong'], ['光頭','guang tou'],
  ['禿頭','tu tou'], ['假髮','jia fa'], ['假牙','jia ya'], ['假貨','jia huo'], ['假死','jia si'], ['家暴','jia bao'], ['夾死','jia si'],
  ['木頭','mu tou'], ['石頭','shi tou'], ['拳頭','quan tou'], ['枕頭','zhen tou'], ['蓬頭','peng tou'], ['搖頭','yao tou'], ['剃頭','ti tou'],
  ['砍頭','kan tou'], ['斷頭','duan tou'], ['人頭','ren tou'], ['牙齒','ya chi'], ['牙齦','ya yin'], ['鴨子','ya zi'], ['猴子','hou zi'],
  ['螺絲','luo si'], ['駱駝','luo tuo'], ['青蛙','qing wa'], ['蜻蜓','qing ting'], ['河馬','he ma'], ['河童','he tong'], ['和尚','he shang'],
  ['尼姑','ni gu'], ['乩童','ji tong'], ['道士','dao shi'], ['牧師','mu shi'], ['傭人','yong ren'], ['童工','tong gong'], ['伯母','bo mu'],
  ['姨媽','yi ma'], ['晚娘','wan niang'], ['媒婆','mei po'], ['煤炭','mei tan'], ['灰燼','hui jin'], ['穢物','hui wu'], ['賄賂','hui lu'],
  ['毀容','hui rong'], ['毀滅','hui mie'], ['塵埃','chen ai'], ['微塵','wei chen'], ['沼澤','zhao ze'], ['洪水','hong shui'], ['濁水','zhuo shui'],
  ['沖走','chong zou'], ['沖掉','chong diao'], ['蒸發','zheng fa'], ['溶解','rong jie'], ['熔化','rong hua'], ['碰壁','peng bi'], ['膨脹','peng zhang'],
  ['腫脹','zhong zhang'], ['硬幣','ying bi'], ['硬塊','ying kuai'], ['影子','ying zi'], ['泡沫','pao mo'], ['破洞','po dong'], ['缺口','que kou'],
  ['花費','hua fei'], ['花圈','hua quan'], ['滑倒','hua dao'], ['摸魚','mo yu'], ['墨魚','mo yu'], ['魔鬼','mo gui'], ['魔王','mo wang'],
  ['末日','mo ri'], ['陌生','mo sheng'], ['抹殺','mo sha'], ['沒落','mo luo'], ['迷路','mi lu'], ['密告','mi gao'], ['耗盡','hao jin'],
  ['好色','hao se'], ['好死','hao si'], ['號哭','hao ku'], ['嚎叫','hao jiao'], ['豪賭','hao du'], ['開刀','kai dao'], ['開槍','kai qiang'],
  ['關門','guan men'], ['關押','guan ya'], ['罐頭','guan tou'], ['灌腸','guan chang'], ['觀落陰','guan luo yin'], ['慣犯','guan fan'],
  ['宣判','xuan pan'], ['懸案','xuan an'], ['懸崖','xuan ya'], ['旋渦','xuan wo'], ['陣痛','zhen tong'], ['針筒','zhen tong'], ['診斷','zhen duan'],
  ['震驚','zhen jing'], ['真假','zhen jia'], ['鎮壓','zhen ya'], ['掙扎','zheng zha'], ['爭吵','zheng chao'], ['症狀','zheng zhuang'], ['整形','zheng xing'],
  ['整容','zheng rong'], ['過期','guo qi'], ['過勞','guo lao'], ['過失','guo shi'], ['得罪','de zui'], ['患病','huan bing'], ['幻覺','huan jue'],
  ['荒廢','huang fei'], ['慌張','huang zhang'], ['蝗蟲','huang chong'], ['殉情','xun qing'], ['殉職','xun zhi'], ['訓斥','xun chi'], ['熏黑','xun hei'],
  ['尖叫','jian jiao'], ['減肥','jian fei'], ['見血','jian xue'], ['漸凍','jian dong'], ['閒人','xian ren'], ['現世','xian shi'], ['鮮血','xian xue'],
  ['線香','xian xiang'], ['顯靈','xian ling'], ['限制','xian zhi'], ['停電','ting dian'], ['停止','ting zhi'], ['停擺','ting bai'], ['舔腳','tian jiao'],
  ['添亂','tian luan'], ['折壽','zhe shou'], ['遮羞','zhe xiu'], ['棄嬰','qi ying'], ['棄權','qi quan'], ['氣喘','qi chuan'], ['奇怪','qi guai'],
  ['騎馬','qi ma'], ['妻子','qi zi'], ['汽油','qi you'], ['責備','ze bei'], ['責罵','ze ma'], ['藥丸','yao wan'], ['藥物','yao wu'], ['配種','pei zhong'],
  ['敏感','min gan'], ['悶死','men si'], ['寒酸','han suan'], ['含淚','han lei'], ['旱災','han zai'], ['憾事','han shi'], ['漢奸','han jian'],
  ['生氣','sheng qi'], ['生蛋','sheng dan'], ['生鏽','sheng xiu'], ['生瘡','sheng chuang'], ['剩下','sheng xia'], ['聲嘶','sheng si'], ['癢癢','yang yang'],
  ['養豬','yang zhu'], ['陽具','yang ju'], ['想死','xiang si'], ['相剋','xiang ke'], ['相親','xiang qin'], ['箱子','xiang zi'], ['象鼻','xiang bi'],
  ['錢包','qian bao'], ['潛逃','qian tao'], ['遣散','qian san'], ['淺薄','qian bo'], ['牽牛','qian niu'], ['狼狗','lang gou'], ['浪蕩','lang dang'],
  ['捉姦','zhuo jian'], ['拙劣','zhuo lie'], ['轟炸','hong zha'], ['哄騙','hong pian'], ['紅腫','hong zhong'], ['動物','dong wu'], ['凍傷','dong shang'],
  ['洞穴','dong xue'], ['東西','dong xi'], ['猿猴','yuan hou'], ['遠離','yuan li'], ['怨氣','yuan qi'], ['種豬','zhong zhu'], ['終結','zhong jie'],
  ['終止','zhong zhi'], ['菌類','jun lei'], ['軍火','jun huo'], ['菌種','jun zhong'], ['光屁股','guang pi gu'], ['逛街','guang jie'],
  ['衝突','chong tu'], ['寵物','chong wu'], ['重複','chong fu'], ['封鎖','feng suo'], ['風濕','feng shi'], ['風寒','feng han'], ['縫合','feng he'],
  ['瘋癲','feng dian'], ['諷刺','feng ci'], ['黏液','nian ye'], ['念經','nian jing'], ['吻別','wen bie'], ['聞臭','wen chou'], ['溫吞','wen tun'],
  ['紋身','wen shen'], ['借錢','jie qian'], ['結巴','jie ba'], ['節哀','jie ai'], ['揭穿','jie chuan'], ['人肉','ren rou'], ['忍痛','ren tong'],
  ['任性','ren xing'], ['鷹爪','ying zhua'], ['應酬','ying chou'], ['如廁','ru ce'], ['蠕動','ru dong'], ['死角','si jiao'], ['撕票','si piao'],
  ['撕裂','si lie'], ['思春','si chun'], ['私通','si tong'], ['月子','yue zi'], ['越軌','yue gui'], ['消失','xiao shi'], ['消滅','xiao mie'],
  ['銷魂','xiao hun'], ['蕭條','xiao tiao'], ['孝服','xiao fu'], ['匪徒','fei tu'], ['非法','fei fa'], ['通通','tong tong'], ['痛哭','tong ku'],
  ['同居','tong ju'], ['銅臭','tong chou'], ['桶子','tong zi'], ['隕石','yun shi'], ['隕落','yun luo'], ['運屍','yun shi'], ['孕婦','yun fu'],
  ['熨斗','yun dou'], ['暈眩','yun xuan'], ['醫院','yi yuan'], ['議員','yi yuan'], ['疑犯','yi fan'], ['異物','yi wu'], ['易怒','yi nu'],
  ['蟻穴','yi xue'], ['異形','yi xing'], ['遺失','yi shi'], ['易碎','yi sui'], ['溢出','yi chu'], ['已死','yi si'], ['疑心','yi xin'],
  ['橫禍','heng huo'], ['拼命','pin ming'], ['貧民','pin min'], ['書呆','shu dai'], ['鼠輩','shu bei'], ['樹皮','shu pi'], ['疏離','shu li'],
  ['輸血','shu xue'], ['子彈','zi dan'], ['姿勢','zi shi'], ['滋事','zi shi'], ['弱小','ruo xiao'], ['檸檬','ning meng'], ['寧死','ning si'],
  ['清蒸','qing zheng'], ['情人','qing ren'], ['傾家','qing jia'], ['情傷','qing shang'], ['銳器','rui qi'], ['驚嚇','jing xia'], ['驚魂','jing hun'],
  ['井底','jing di'], ['靜脈','jing mai'], ['淋雨','lin yu'], ['臨終','lin zhong'], ['臨死','lin si'], ['剝皮','bo pi'], ['薄命','bo ming'],
  ['薄情','bo qing'], ['駁回','bo hui'], ['喝酒','he jiu'], ['核彈','he dan'], ['盒子','he zi'], ['芝麻','zhi ma'], ['窒息','zhi xi'],
  ['指甲','zhi jia'], ['脂肪','zhi fang'], ['至死','zhi si'], ['致死','zhi si'], ['致命','zhi ming'], ['執迷','zhi mi'], ['穿幫','chuan bang'],
  ['傳染','chuan ran'], ['喘氣','chuan qi'], ['串通','chuan tong'], ['力竭','li jie'], ['例假','li jia'], ['立刻','li ke'], ['離奇','li qi'],
  ['離開','li kai'], ['離去','li qu'], ['離家','li jia'], ['離散','li san'], ['李子','li zi'], ['理賠','li pei'], ['理髮','li fa'], ['利息','li xi'],
  ['踩死','cai si'], ['猜疑','cai yi'], ['財迷','cai mi'], ['裁員','cai yuan'], ['委屈','wei qu'], ['萎縮','wei suo'], ['衛生','wei sheng'],
  ['尾巴','wei ba'], ['偽裝','wei zhuang'], ['偽鈔','wei chao'], ['畏縮','wei suo'], ['圍毆','wei ou'], ['味精','wei jing'], ['危樓','wei lou'],
  ['照妖','zhao yao'], ['找碴','zhao cha'], ['招惹','zhao re'], ['眼淚','yan lei'], ['咽氣','yan qi'], ['演戲','yan xi'], ['淹水','yan shui'],
  ['煙癮','yan yin'], ['嚴刑','yan xing'], ['鹽巴','yan ba'], ['甲蟲','jia chong'], ['加害','jia hai'], ['價錢','jia qian'], ['舔屁','tian pi'],
  // 以 li 結尾（給「名2＋李」英文順序、「名1＋李」用）
  ['成立','cheng li'], ['病例','bing li'], ['暴力','bao li'], ['無力','wu li'], ['無理','wu li'], ['無禮','wu li'], ['吃力','chi li'],
  ['費力','fei li'], ['乏力','fa li'], ['失利','shi li'], ['失禮','shi li'], ['勢利','shi li'], ['阻力','zu li'], ['苦力','ku li'],
  ['勞力','lao li'], ['分離','fen li'], ['距離','ju li'], ['逃離','tao li'], ['隔離','ge li'], ['脫離','tuo li'], ['剝離','bo li'],
  ['玻璃','bo li'], ['修理','xiu li'], ['護理','hu li'], ['料理','liao li'], ['處理','chu li'], ['清理','qing li'], ['整理','zheng li'],
  ['助理','zhu li'], ['代理','dai li'], ['經理','jing li'], ['總理','zong li'], ['監理','jian li'], ['鴨梨','ya li'], ['鳳梨','feng li'],
  ['雪梨','xue li'], ['水梨','shui li'], ['茉莉','mo li'], ['狐狸','hu li'], ['奴隸','nu li'], ['犀利','xi li'], ['私利','si li'],
  ['暴利','bao li'], ['牟利','mou li'], ['壓力','ya li'], ['暴戾','bao li'], ['乖戾','guai li'], ['慘厲','can li'], ['厲厲','li li'],
  ['沒道理','mei dao li'], ['不合理','bu he li'], ['沒能力','mei neng li'], ['無能力','wu neng li'], ['好無力','hao wu li'], ['很無力','hen wu li'],
  ['沒魅力','mei mei li'], ['沒體力','mei ti li'], ['不給力','bu gei li'], ['太吃力','tai chi li'], ['被隔離','bei ge li'], ['要分離','yao fen li'],
  // 以常見姓氏結尾（英文順序用）：王 wang、陳 chen、林 lin、黃 huang、吳 wu、劉 liu、張 zhang
  ['死亡','si wang'], ['滅亡','mie wang'], ['逃亡','tao wang'], ['陣亡','zhen wang'], ['絕望','jue wang'], ['失望','shi wang'], ['妄想','wang xiang'],
  ['灰塵','hui chen'], ['粉塵','fen chen'], ['下沉','xia chen'], ['深沉','shen chen'], ['陰沉','yin chen'], ['遲鈍','chi dun'],
  ['森林','sen lin'], ['山林','shan lin'], ['雨淋','yu lin'], ['濕淋','shi lin'], ['光臨','guang lin'], ['降臨','jiang lin'],
  ['發黃','fa huang'], ['蛋黃','dan huang'], ['慌慌','huang huang'], ['蟑螂','zhang lang'], ['虛無','xu wu'], ['烏烏','wu wu'], ['嗚嗚','wu wu'],
  ['漂流','piao liu'], ['逆流','ni liu'], ['暗流','an liu'], ['下流','xia liu'], ['支流','zhi liu'], ['緊張','jin zhang'], ['囂張','xiao zhang'], ['誇張','kua zhang'],
  // 三字（含姓氏才對得到）
  ['肚子疼','du zi teng'], ['豬一群','zhu yi qun'], ['衛生巾','wei sheng jin'], ['熊出沒','xiong chu mo'], ['來月經','lai yue jing'],
  ['禽獸生','qin shou sheng'], ['理不清','li bu qing'], ['離不開','li bu kai'], ['你媽的','ni ma de'], ['沒人愛','mei ren ai'],
];
